# Generated by Django 2.2.4 on 2019-09-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipdata_model',
            options={'managed': False},
        ),
    ]
