# Generated by Django 2.2.4 on 2020-05-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddles', '0002_auto_20190928_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputCommandsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_line', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Progress_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50)),
                ('score', models.IntegerField()),
                ('kol_lessons', models.IntegerField()),
                ('all_answers', models.IntegerField()),
                ('good_answers', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ipdata_model',
        ),
    ]
